version: '3'
services:
    db:
        image: mysql:5.6.51
        container_name: db
        environment: 
            MYSQL_ROOT_HOST: '%'
            MYSQL_DATABASE: record_and_play
            MYSQL_ROOT_PASSWORD: klnmdas89312onlfpgadlsvcm
        restart: unless-stopped
        command: "mysqld --default-authentication-plugin=mysql_native_password"
        volumes:
            - /var/lib/rp/mysql5.0.6:/var/lib/mysql
        ports:
            - 3306:3306
        networks:
            - app-network
    api:
        build: .
        depends_on:
          - db
        networks:
          - app-network
        ports:
            - 3000:3000
networks:
  app-network:
    driver: bridge