version: '3'
services:
    db:
        image: mysql:5.6.51
        container_name: db
        environment: 
            MYSQL_ROOT_HOST: '%'
            MYSQL_DATABASE: record_and_play
            MYSQL_ROOT_PASSWORD: klnmdas89312onlfpgadlsvcm
        restart: unless-stopped
        command: "mysqld --default-authentication-plugin=mysql_native_password"
        volumes:
            - /var/lib/mysql5.0.6:/var/lib/mysql
        ports:
            - 3306:3306
        networks:
            - app-network
networks:
  app-network:
    driver: bridge