version: '3'

services:

  pgdb:
    image: postgres
    environment:
      POSTGRES_USERNAME: "postgres"
      POSTGRES_PASSWORD: "postgres"
      POSTGRES_DB: "waving_test"
    ports:
      - "15432:5432"
    volumes:
      - postgres:/var/lib/postgresql/data
    networks:
      - app-network
    restart: unless-stopped

  pgadmin:
    image: dpage/pgadmin4
    environment:
      PGADMIN_DEFAULT_EMAIL: "str@atlantico.com.br"
      PGADMIN_DEFAULT_PASSWORD: "SrtAdmin2021!"
    ports:
      - "16543:80"
    volumes:
      - pgadmin:/var/lib/pgadmin
    depends_on:
      - pgdb
    networks:
      - app-network
    restart: unless-stopped

  mysqldb:
    image: mysql:5.6.51
    container_name: db
    environment:
      MYSQL_ROOT_HOST: '%'
      MYSQL_DATABASE: waving_test
      MYSQL_ROOT_PASSWORD: klnmdas89312onlfpgadlsvcm
    restart: unless-stopped
    command: "mysqld --default-authentication-plugin=mysql_native_password"
    volumes:
      - /var/lib/wt/mysql5.0.6:/var/lib/mysql
    ports:
      - 3306:3306
    networks:
      - app-network

  api:
    build: .
    depends_on:
      - pgdb
    networks:
      - app-network
    ports:
      - 3000:3000

networks:
  app-network:
    driver: bridge

volumes:
  postgres:
  pgadmin:
